[package]
name = "lnxparser"
version = "0.1.0"
edition = "2021"

[lib]
name = "lnxparser"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnet = "2.8.0"
